CREATE TABLE IF NOT EXISTS debtor_rankings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cuit VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    amount DECIMAL(15, 2),
    status ENUM('RED', 'YELLOW', 'GREEN') DEFAULT 'RED',
    is_forced BOOLEAN DEFAULT FALSE,
    forced_position INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
